name: PEP8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: App
      run: |
        ruff check --statistics --preview app.py
        ruff format --check --preview app.py
    - name: lib
      run: |
        ruff check --preview --statistics fink_watch/*.py
        ruff format --check --preview fink_watch/*.py
